### ISSUE TITLE
REGARDING LIPO 3.7V  with embedded NTC

### ISSUE THREAD

**Issue by Ganeshvadhri** [romainrossi/make_your_robot_tick#11]
Where will we get a 3.7v lipo battery with embedded NTC?
It is mentioned in schematics of SAMboard that  we could short the GS pin if we want to connect a lipo battery without NTC, but we could not find the GS pin anywhere on the board.

**Comment by romainrossi** [comment]
Due to safety problems, air-shipping of LiPo battery is now becoming very difficult and expensive. This is why the robot we provided don't have the embedded battery which we normally use.

To power the robot, you can use (by order of preference) :

1. A smartphone portable power bank (best method)
2. A LiPo battery pack with embedded NTC (best alternative)
3. A LiPo battery pack without NTC (discouraged)

**Solution 1** is easier, quicker and safer. A small and cheap smartphone power bank connected to the charging port of the SAMboard will be enough; provided it can output 5V at 1A (virtually all power banks can do that) and have a capacity of 1000 mA.h or more. I suggest you get two small power banks instead of a big one, so you can quickly swap it when it is depleted (instead of waiting to recharge it). The smallest power bank you can find should be ok thanks to the low power consumption of the robot.

**Solution 2** needs a battery pack of 3.7V, 1300mA.h with a 3 point connector. [Official LiPo battery we use on the SAMboard](https://fr.farnell.com/bak/lp-503759-is-3/batterie-lithium-pol-3-7v-1300/dp/2077882?krypto=6tRzZiMA5rssqt9jJ7cVPy9F%2BM7mbofBlUGwd5mQM2SKhnGewerAFP2RBaNL3DyfCE01ZwERBubbaU3aBe0CTQ%3D%3D&ddkey=https%3Afr-FR%2FElement14_France%2Fsearch). You need to pay attention to the connector (type and connections). The battery can be attached underneath the robot with adhesive pad. The battery is charged when 5V is supplied to the USB connector on the SAMboard.

**Solution 3** is discouraged. With a hardware modification of the SAMboard (removing the battery connector, replacing it with a 2 points connector, and shorting GS). The SAMboard can use a LiPo battery without NTC (2 points connector). The battery must have exactly this characteristics : 3.7V, 1300mA.h with the same size as the previous battery (see solution 2). This solution has not been tested.
