### ISSUE TITLE
LIMITING RESISTOR

### ISSUE THREAD

**Issue by Ganeshvadhri** [romainrossi/make_your_robot_tick#18]
1) Does the limiting resistance vary for a source , or is it constant?
2) In the grading pattern it is given that , if the energy delivered by the fast charging station is completely delivered to the ESS 500 points are awarded respectively 250 points for the accelerated and 66 points for the regular station.So, how do you differentiate between how much energy is being delivered  from the 3 different sources to calculate the points

**Comment by romainrossi** [comment]
The full electrical schematics are available in this github repository (directory src/elec). It's made with KiCAD, a free and open-source software.
As you can see on the schematics, each source is equipped with a different fixed resistor which will provide the different current settings. The current for each source is fixed; but remember sources are enabled with a given time-schedule during the match (see RuleBook Figure 5 page 5).

The Energy Storage System (ESS) gives points for each quantity of energy delivered. It can't know from which source the energy come from; and your robot can have charged to multiple sources before delivering energy to the ESS. However, the mathematical relationship between Energy and Points is calibrated in the ESS so that if your robot gather **all** the energy delivered by the Fast Source during the whole match and deliver it to the ESS, it will give 500 points. Based on the relative amount of energy delivered by the other sources, we can estimate the number of points.

Source | Limiting resistor | Max current | ON time | Quantity of energy (C) | Max points |
--- | --- | --- | ---| ---| ---|
Regular | 500 | 10mA | 240s | 2.4 | 176 |
Accelerated | 100 | 50mA | 75s | 3.75 | 275 |
Fast | 33 | 150mA | 45s | 6.81 | 500 (by calibration) |
