### ISSUE TITLE
Competition timeline and availability of the development board

### ISSUE THREAD

**Issue by shubham-rateria982** [romainrossi/make_your_robot_tick#2]
The rule book states that each team is required to send a **document containing the technical specifications** to the organizers. By when is this to be done?
Also, we would like to know a rough timeline of events of the rounds of the competition.
We were also informed that all participants will receive a mobile platform [ the SAMboard] with basic parts on which we can build our robot. Could you please tell us by when are we going to receive the same?

Thank you.

**Comment by romainrossi** [comment]
# Technical specifications document

As stated in the rules book (page 2, section 1.2.1) :

> Each team will submit a technical specifications document to the Organising Committee. The format and deadlines will be indicated on the website of the competition.
> This document will provide the overview of the project with a focus on:
> * General information: Team information
> * Technical specifications:
>   * Strategy
>   * Technical choices
>   * Hardware architecture and schematics
>   * Algorithms
>
> Note: This document must be submitted to the organising committee one month prior to the competition.

The competition finale will take place on the **4th of October 2018**, the submission of the Technical Specification document by each teams must be done on the **4th september 2018**.

# Rough timeline

At this point in time, selected teams must design, build and program their robots for the competition finale. This finale will be a one-day event, with a qualifying round and a final round organized as decribed in the Rulebook (page 9 to 11).

# Mobile Platform

The shipping of the mobile platforms is delayed because of the hollidays. Shipping will be done during the second half of August.

In the meantime, full documentation about the platform is available in the github repository and can be used as reference to design and build your add-on board.
